language: php

dist: precise

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0
  - 7.1

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script: vendor/bin/phpunit