name: headers

on:
    pull_request: ~
    push:
        branches:
            - master

jobs:
    tests-php-8-1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
            - name: PHPUnit
              run: |
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
    tests-php-8-2:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
            - name: PHPUnit
              run: |
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
